# Generated by Django 4.2.8 on 2023-12-23 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='No_og_guests',
        ),
        migrations.AddField(
            model_name='booking',
            name='No_of_guests',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='inventry',
            field=models.IntegerField(),
        ),
    ]
